version: "3.3"
services:
    mongo:
        image: 'mongo'
        container_name: 'letmeknow-mongo-db'
        ports:
            - 27017:27017
        volumes:
            - mongo:/data/db
volumes:
    mongo: